version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: asmae123
      MYSQL_DATABASE: mysql_server
      MYSQL_USER: intern_asmae
      MYSQL_PASSWORD: asmae123
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"

  grafana:
    image: grafana/grafana
    container_name: grafana_new
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
     - ./config/grafana.ini:/etc/grafana/grafana.ini
  
  tracking-server:
      build: .
      ports:
        - "5000:5000"
      environment:
        - MLFLOW_TRACKING_URI=mysql://intern_asmae:asmae123@db:3306/mysql_server
      depends_on:
        - db


volumes:
  db_data:
