"""initial migration

Revision ID: a7212cee07ec
Revises: 
Create Date: 2024-05-30 09:34:15.893960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7212cee07ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DulangTagList',
    sa.Column('tagID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('type', sa.String(length=200), nullable=True),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('sapmapping', sa.String(length=200), nullable=True),
    sa.Column('upperlimit', sa.Float(), nullable=True),
    sa.Column('lowlimit', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('tagID'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('CGCE7K',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tagID', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tagID'], ['DulangTagList.tagID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CGCE7K')
    op.drop_table('DulangTagList')
    # ### end Alembic commands ###
